### PR TITLE
missing attrs should raise attribute errors.

### PR DESCRIPTION
**Pull request by Hellowlol**
This just so travis test the pr.

### CODE REVIEW

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/issues/206

**Comment by Hellowlol** [comment]
hmm, seems like we should a bug in the tests. As far as i can see there is no .player but since every missing attributes has returned None this has passed.

**Comment by Hellowlol** [comment]
I'll fix the failing tests and merge this 👍

**Comment by pkkid** [comment]
Don't merge this yet. It's a very touchy part of the code and I want to take a look at it. For example: I think player is only an attribute in some cases (ie: actively playing sessions).

**Comment by Hellowlol** [comment]
Alright, I'll wait for your approval. I think your wrong. I can only find players. I think player is a typo that has been copy pasted around in the tests

**Comment by pkkid** [comment]
You're probably right then. I'm going off memory. This is a great improvement, I'm just nervous because as you mentioned before.. dragons.

**Comment by Hellowlol** [comment]
Have you had time to test this?

**Comment by pkkid** [comment]
I haven't. It's going to be a bit as things are pretty busy at work these weeks. -- How did you handle the case when viewCount is zero it's not actually an attribute on the item?

**Comment by Hellowlol** [comment]
I havnet really thought about about viewCount but since we hate using .get"viewCount", 0) it should always have a value. I think one of ous test would have failed nevertheless I'm gonna make a test just for that and fix the .player

**Comment by pkkid** [comment]
If we have to write special code to make viewCount work, it makes me wonder if there are other attributes similar to it that hide when equal to 0, false, inactive, etc. -- If it comes to it, we may be can account for missing attrs in the utils.cast function; its a good place where we know we want to populate an attribute, weather we see it in the data or not.

**Comment by Hellowlol** [comment]
Seems to be working fine now 👍

**Comment by pkkid** [comment]
:+1:

**Pull request merged**
