### PR TITLE
Fix and update library searching

### LINKED ISSUE #320: search **kwargs with also != > <
Hello,
is it possible add the search not only for = but also for > or != or <  ?

example:
music = plex.library.section('Musica')
for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",genre != 'Pop') : #not

for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",genre = 'Pop') : #contain

for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",genre == 'Pop') : # equal

for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",year > 1970) : # major

### LINKED ISSUE #392: ALLOWED_FILTERS do not accept OPERATORS when using search
```python
music = plex.library.section("Music")
test = music.searchTracks(**{'track.skipCount': 1})
print(test) # results!
```
vs
```python
music = plex.library.section("Music")
test = music.searchTracks(**{'track.skipCount__gte': 1})
print(test) # Unknown filter category: track.skipCount__gte
```

Appending the operator to the filter name for the used section works as intended.

```python
# MusicSection / ALLOWED_FILTERS = (..., 'track.skipCount>>', ...)
music = plex.library.section("Music")
test = music.searchTracks(**{'track.skipCount>>': 1}) # equal or greater than
print(test) # intended results!
```

Seems like there may need to have an additional CUSTOM_FILTERS list for each library section class and have the ALLOWED_FILTERS for each libtype (grandparent, parent, child). CUSTOM_FILTERS would need to be able to have use of OPERATORS. 

Plex uses exact matching for libtype filtering and allows for operators in custom filter of the library. How close should `plex.search()` be to Plex's WebUI ilibtype filters and custom filters?

### LINKED ISSUE #553: LibrarySection.search documentation does not list `artist`
The documentation of `LibrarySection.search` does not list `artist` as a possible field to search for ([proof](https://python-plexapi.readthedocs.io/en/latest/_modules/plexapi/library.html#LibrarySection.search)). This seems rather odd. 
Is this an oversight in the documentation, and the field is actually supported, or is this an actual shortcoming of the API or its implementation?

### LINKED ISSUE #595: having trouble with searching using filter!
I'm trying to use [LibrarySection.search](https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.search) to search using ! in the search filter and when I add the ! after actor, country, director, genre, and writer no matter what value I give it, it just returns every movie in my library. studio! and year! seemed to work but i haven't tested any other filters other then the ones mentioned in this post. what i ran to test is belowis below

```python
def test(filters):
    print(str(filters) + ": " + str(len(plex.Library.search(**filters))))

test({'actor': 'Will Smith'})
test({'actor!': 'Will Smith'})
test({'country': 'USA'})
test({'country!': 'USA'})
test({'director': 'Steven Spielberg'})
test({'director!': 'Steven Spielberg'})
test({'genre': 'Romance'})
test({'genre!': 'Romance'})
test({'genre': 'Comedy'})
test({'genre!': 'Comedy'})
test({'studio': 'Pixar'})
test({'studio!': 'Pixar'})
test({'year': '1990'})
test({'year!': '1990'})
test({'writer': 'Quentin Tarantino'})
test({'writer!': 'Quentin Tarantino'})
```

Output
```
{'actor': 'Will Smith'}: 21
{'actor!': 'Will Smith'}: 1780
{'country': 'USA'}: 1489
{'country!': 'USA'}: 1780
{'director': 'Steven Spielberg'}: 16
{'director!': 'Steven Spielberg'}: 1780
{'genre': 'Romance'}: 107
{'genre!': 'Romance'}: 1780
{'genre': 'Comedy'}: 603
{'genre!': 'Comedy'}: 1780
{'studio': 'Pixar'}: 9
{'studio!': 'Pixar'}: 1771
{'year': '1990'}: 15
{'year!': '1990'}: 1765
{'writer': 'Quentin Tarantino'}: 12
{'writer!': 'Quentin Tarantino'}: 1780
```

Am i doing something wrong or is this feature not working correctly?

### LINKED ISSUE #623: libtype not handled properly for ShowSection search with kwargs
I was trying to run the following:
```
shows = plex.library.section('Shows')
for show in shows.searchShows(unwatchedLeaves = True):
    print(show.title)
```
and I receive the following error:
```
    for show in shows.searchShows(unwatchedLeaves = True):
  File "C:\Program Files\Python36\lib\site-packages\plexapi\library.py", line 907, in searchShows
    return self.search(libtype='show', **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\plexapi\library.py", line 669, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "C:\Program Files\Python36\lib\site-packages\plexapi\library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: unwatchedLeaves
```

When I delved into the code I saw: 
https://github.com/pkkid/python-plexapi/blob/master/plexapi/library.py#L718-723
```
categories = [x.key for x in self.filterFields()]
...
elif category not in categories
```
And it looks like at this point, based on the key values of `.filterFields()` the `category` has to be `show.unwatchedLeaves` to not throw an error. I also tried making that my kwarg (`shows.searchShows(show.unwatchedLeaves = True)` but python did not like that at all.

It seems like the libtype needs to be appended on the front of the category at some point?

### LINKED ISSUE #691: .search(unwatched=True) broken with recent PMS update
**Describe the issue**

Even with the updates outlined in #623, these appear to be broken again with the recent update to Plex 1.22.0.4163. I'd appreciate someone confirming or denying that this is working.

**Code snippets**

for currentSection in plexServer.library.sections():
	if currentSection.type == 'movie':
		unwatchedLibraryItems = currentSection.search(unwatched=True)
	elif currentSection.type == 'video':
		unwatchedLibraryItems = currentSection.search(unwatched=True)
	elif currentSection.type == 'show':
		unwatchedLibraryItems = currentSection.searchEpisodes(**{'episode.unwatched':True})

This worked before.

**Expected behavior**

Successful search, results returned. Instead:

[3/10/2021 3:10:25 PM] [python.exe]:   File "C:\Python\lib\site-packages\plexapi\library.py", line 717, in _cleanSearchFilter
[3/10/2021 3:10:25 PM] [python.exe]:     raise BadRequest('Unknown filter category: %s' % category)
[3/10/2021 3:10:25 PM] [python.exe]: plexapi.exceptions.BadRequest: Unknown filter category: unwatched

**Enviroment (please complete the following information):**
 - OS: Windows 10
 - Plex version 1.22.0.4163
 - Python Version Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
 - PlexAPI version 4.3.1

**Additional context**

### LINKED ISSUE #694: Library search breaks early when using a PlexAPI operator
**Describe the issue**
The current library search loop breaks when no results are found.

https://github.com/pkkid/python-plexapi/blob/4.4.1/plexapi/library.py#L691

If a PlexAPI operator is used (e.g. `viewCount__gt=0`), the first batch of results may return 0 results (i.e. There are no items with a view count greater than 1 in the first 100 items (`container_size`)). This causes the loop to break without continuing the search through the rest of the items.

**Code snipppets**
```python
>>> library = plex.library.section("TV Shows")
>>> results = library.search(libtype='episode', container_size=1, viewCount__gte=0)
>>> print(len(results))
0
```
image

**Expected behavior**
Search should continue looping through the rest of the items.

Proposed solution is to add a check if the container exceeds the total number of items to exit the loop.

https://github.com/pkkid/python-plexapi/blob/4.4.1/plexapi/library.py#L707

```python
if container_start > self.totalSize:
    break
```

**Enviroment (please complete the following information):**
 - PlexAPI version: 4.4.1

### LINKED ISSUE #695: Library totalSize overwritten when using search with libtype
**Describe the issue**
The library cached `_total_size` value is overwritten when using search with a different `libtype` than the main library type.

https://github.com/pkkid/python-plexapi/blob/4.4.1/plexapi/library.py#L380

This causes the `totalSize` property to return the cached value instead of the correct value.

https://github.com/pkkid/python-plexapi/blob/4.4.1/plexapi/library.py#L393

**Code snipppets**
```python
>>> library = plex.library.section("TV Shows")
>>> print(library.totalSize)
2  # This is the number of TV Shows in the library
>>> library.searchEpisodes()  # This calls library.search(libtype='episode')
>>> print(library.totalSize)
51  # This is now the number of episodes in the library.
```

**Expected behavior**
Library `totalSize` should always be the number of items of the main library type (i.e. number of shows).

**Enviroment (please complete the following information):**
 - PlexAPI version: 4.4.1

### PR DESCRIPTION
**Pull request by JonnyWong16**
## Description

This is a complete rewrite of the library search feature. See doc string for `LibrarySection.search()` for complete details and examples.

**Deprecated methods**
* `LibrarySection.filterFields()`: use `listFields()` instead.
* `LibrarySection.listChoices()`: use `listFilterChoices()` instead.

**New methods**
See doc strings for each method for complete details and examples.

* `LibrarySection.filterTypes()`
* `LibrarySection.getFilterType()`
* `LibrarySection.fieldTypes()`
* `LibrarySection.getFieldType()`
* `LibrarySection.listFilters()`
* `LibrarySection.listSorts()`
* `LibrarySection.listFields()`
* `LibrarySection.listOperators()`
* `LibrarySection.listFilterChoices()`
* `LibrarySection.hubSearch()`: alias for `PlexServer.search(query, sectionId=librarySectionID)`
* `MovieSection.searchMovies()`: alias for `LibrarySection.search(libtype='movie')`
* `ShowSection.searchSeasons()`: alias for `LibrarySection.search(libtype='season')`

**Breaking changes**
* `librarySectionID` is casted to an `int` everywhere instead of a `str`
* `LibrarySection.filters` is casted to a `bool` instead of a `str`
* `LibrarySection.key` is casted to a `int` instead of a `str`

Closes #598

Fixes #320
Fixes #392
Fixes #553
Fixes #595
Fixes #623
Fixes #691
Fixes #694
Fixes #695

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods
- [x] I have added tests when applicable

### CODE REVIEW

**Comment by meisnate12** [comment]
saw this and started playing with the update to see what it could do and when I try this:
```python
ps = PlexServer("http://IP.IP.IP.IP:32400", "thisisnotmytoken", timeout=600)
plex = next((s for s in ps.library.sections() if s.title == "TV Shows"), None)
items = plex.search(**{"genre": "Comedy"})
print(items)
```

i get the error
```
  File "C:\Users\meisn\Documents\Python\Plex Meta Manager\test.py", line 67, in <module>
    items = plex.search(**{"show.genre": "Comedy"})
  File "C:\Users\meisn\Documents\Python\Plex Meta Manager\venv\lib\site-packages\plexapi\library.py", line 1064, in search
    filter_args.append(self._validateFilterField(field, values, libtype))
  File "C:\Users\meisn\Documents\Python\Plex Meta Manager\venv\lib\site-packages\plexapi\library.py", line 768, in _validateFilterField
    result = self._validateFieldValue(filterField, values, libtype)
  File "C:\Users\meisn\Documents\Python\Plex Meta Manager\venv\lib\site-packages\plexapi\library.py", line 811, in _validateFieldValue
    filterChoices = self.listFilterChoices(filterField.key, libtype)
  File "C:\Users\meisn\Documents\Python\Plex Meta Manager\venv\lib\site-packages\plexapi\library.py", line 735, in listFilterChoices
    raise NotFound('Unknown filter: %s. '
plexapi.exceptions.NotFound: Unknown filter: show.genre. Available filters: ['genre', 'year', 'contentRating', 'studio', 'collection', 'director', 'actor', 'writer', 'producer', 'unwatchedLeaves', 'unmatched', 'label']
```

if I change `items = plex.search(**{"genre": "Comedy"})` to `items = plex.search(**{"show.genre": "Comedy"})`
I get the exact same error

also, I tried specifying the `libtype="show"` and received the same error message

**Comment by JonnyWong16** [comment]
Try it now. Let me know if you find any other errors.

**Comment by meisnate12** [comment]
ok it works now I'm working on an update for my program for once this comes out if I find anything else I'll let you know

**Comment by meisnate12** [comment]
ok so now im trying to use the `&` operator this is my code
```python
ps = PlexServer("http://IP.IP.IP.IP:32400", "thisisnotmytoken", timeout=600)
plex = next((s for s in ps.library.sections() if s.title == "Movies"), None)
print(len(plex.search(**{"genre": "Comedy"})))
print(len(plex.search(**{"genre": "Action"})))
print(len(plex.search(**{"genre": ["Comedy", "Action"]})))
print(len(plex.search(**{"genre&": ["Comedy", "Action"]})))
print(len(plex.search(**{"genre": "Comedy", "genre&": ["Action"]})))
```
with the results:
```
690    <--- this is the correct number of movies I have with Comedy
702    <--- this is the correct number of movies I have with Action
1254   <--- this is the correct number of movies I have with Comedy or Action
1980   <--- this is my total number of movies in plex according to the plex search in the UI I should have 138 with both Genre tags
690    <--- this is the number of movies I have with Comedy adding the `genre&` did nothing
```

it seems to me that the `&` search isn't working correctly unless I'm using it wrong

**Comment by JonnyWong16** [comment]
Fixed the `&` operator.

**Comment by meisnate12** [comment]
`duration` search doesn't seem to work. I either get all items in my library or 0 items depending on if I use `<<` or `>>` no matter what int I gave it.

**Comment by JonnyWong16** [comment]
I cannot reproduce the issue.
```python
>>> movies = plex.library.section("Movies")
>>> len(movies.all())
1937
>>> duration = 5400000  # 1.5 hours in milliseconds
>>> len(movies.search(**{"duration<<": duration}))
288
>>> len(movies.search(**{"duration>>": duration})) 
1649
```

**Comment by meisnate12** [comment]
ok yea that ones my mess up it does work sorry

**Comment by Hellowlol** [comment]
This looks awesome. Great work!

**Comment by Montellese** [comment]
Thanks for all these changes.

I noticed that your change to split `_totalSize` and `_totalViewSize` has made it impossible to determine how many collections are in a movie section or how many seasons or episodes are in a tvshow section. I need this information to be able to perform paginated search requests. If I access the private `LibrarySection._totalViewSize` member instead of using the public `LibrarySection.totalSize` property everything works fine again. How should we fix / resolve this?

Furthermore I noticed that you changed all library section IDs from `str` to `int` which I like. But the docstring at https://github.com/pkkid/python-plexapi/blob/2bde2344084721d7015167af4762d3bc397fe5d2/plexapi/library.py#L65 still says that the expected `sectionID` is a `str` instead of `int`.

**Comment by JonnyWong16** [comment]
Thanks. See #712.

**Comment by meisnate12** [comment]
I was trying to do a title search using a list like so 

```python
print(len(plex.search(**{"title": "Star"})))                # Worked returned 32
print(len(plex.search(**{"title": "Wars"})))                # Worked returned 16
print(len(plex.search(**{"title": ["Wars"]})))                # Failed returned 0
print(len(plex.search(**{"title": ["Star", "Wars"]})))      # Failed returned 0
print(len(plex.search(**{"title&": ["Star", "Wars"]})))     # Worked returned 13
```

and while getting the correct results for some searches, using a list with title results in 0 items returned. Is there any way to do an OR title search. If not could it be added in? I tried similar tests with the other string I'm using, which is studio, and it was able to or together values ok

**Comment by JonnyWong16** [comment]
That's a bug I missed because `title` is already an argument for `search()` so the`**kwarg` for `title` is not being applied.

This should be a workaround for title `OR` specifically until it's fixed.
```python
plex.search(title="Star,Wars")
```

**Pull request merged**
