### PR TITLE
Allow control of Sonos speakers using Plex API

### PR DESCRIPTION
**Pull request by jjlawren**
Plex offers a Plex Pass feature where Plex clients can control music playback on Sonos speakers directly, bypassing the need for using the Sonos app: https://support.plex.tv/articles/218237558-requirements-for-using-plex-for-sonos/.

These calls go through a Plex cloud service so remote access must be open for the control commands to work properly. However, playback will be direct from Plex server -> speaker unless network issues prevent it (ie, broken rebind protection).

_Note:_ Playback will always be reported as "remote" in the Plex Web status page as playback progress is reported by the Plex service, not the speaker directly.

**Requirements:**

1. Active Plex Pass subscription
2. Sonos linked to Plex account
3. Remote access working on Plex
4. (Possible) Rebind protection mitigated for `plex.direct` DNS domains

This will allow you to control Plex music on your Sonos speakers like so:
```
from plexapi.server import PlexServer
from plexapi.myplex import MyPlexAccount

account = MyPlexAccount(token)
for speaker in account.sonos_speakers():
    print(speaker.title)

server = PlexServer(server_url, token)

album = server.library.section('Music').get('Stevie Wonder').album('Innervisions')

speaker = account.sonos_speaker("Kitchen")
speaker.playMedia(album)

#speaker.pause()
#speaker.setVolume(10)
#speaker.skipNext()
```

### CODE REVIEW

**Comment by Hellowlol** [comment]
Can you document examples and the requirements? Also tests would be great

**Comment by jjlawren** [comment]
Docs updated. Any suggestions on testing the public Plex APIs used? The tests like in `test_myplex.py` don't really seem to test the actual functionality expected, just failure cases.

Perhaps we could mock return some expected XML examples.

**Comment by Hellowlol** [comment]
Mock would be nice.

**Comment by jjlawren** [comment]
@Hellowlol anything else you'd like here?

**Comment by Hellowlol** [comment]
Nope. Everything seems to be in order. I’ll see if I can’t get it merges this weekend.

**Comment by Hellowlol** [comment]
Mind checking https://readthedocs.org/projects/python-plexapi/builds/11011580/

````
looking for now-outdated files... none found
pickling environment... WARNING: autodoc: failed to import module u'myplex'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-plexapi/envs/stable/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-plexapi/checkouts/stable/plexapi/myplex.py", line 15, in <module>
    from plexapi.sonos import PlexSonosClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-plexapi/checkouts/stable/plexapi/sonos.py", line 114
    **params,
````

**Pull request merged**
