### PR TITLE
Add Missing timeout

### LINKED ISSUE #1490: 'PlexSonosClient' object has no attribute '_timeout'
### Describe the Bug

Using the code snippet from the front page I can retrieve my sonos speaker and I was originally able to control it, but for some days whenever I try to execute a command I am facing the following error:

**AttributeError: 'PlexSonosClient' object has no attribute '_timeout'**

### Code Snippets

```python
from plexapi.myplex import MyPlexAccount
from plexapi.server import PlexServer

account = MyPlexAccount('<EMAIL>', '<PASSWORD>')
plex = account.resource('<PLEXINSTANCE>').connect()

# List available speakers/groups
for speaker in account.sonos_speakers():
    print(speaker.title)
    speaker.stop()
```

### Expected Behavior

Stop playing music on (any) sonos speaker.

### Additional Context

Tested this on a raspberry (with python 3.12.3) and from another ubuntu (python 3.11.11). Same error on all instances.

### Operating System and Version

Ubuntu 22.04.5 LTS

### Plex Media Server Version

1.41.3.9314

### Python Version

3.10.14

### PlexAPI Version

4.16.0

### PR DESCRIPTION
**Pull request by chris-rudmin**
_timeout is expected on PlexClient

## Description

Please include a summary of the change and which issue is fixed.

Fixes #1490

## Type of change
Fix PlexSonosClient missing _timeout on self

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

### CODE REVIEW

**Comment by JonnyWong16** [comment]
Could you add `timeout` to the arguments? 

https://github.com/pkkid/python-plexapi/blob/2ed7702e6f461efae7faa4349db1922de1546492/plexapi/client.py#L65-L67

https://github.com/pkkid/python-plexapi/blob/2ed7702e6f461efae7faa4349db1922de1546492/plexapi/client.py#L75

**Comment by chris-rudmin** [comment]
> Could you add `timeout` to the arguments?
> 
> https://github.com/pkkid/python-plexapi/blob/2ed7702e6f461efae7faa4349db1922de1546492/plexapi/client.py#L65-L67
> 
> https://github.com/pkkid/python-plexapi/blob/2ed7702e6f461efae7faa4349db1922de1546492/plexapi/client.py#L75

[08c8496](https://github.com/pkkid/python-plexapi/pull/1489/commits/08c8496bfc8f4ee6058ed7041b8e7dea7aba1730)

**Comment by chris-rudmin** [comment]
Test failures are on master branch and seem unrelated to my changes (tests/test_video.py::test_video_Movie_attrs[anonymously] ). All sonos tests are passing

**Comment by JonnyWong16** [comment]
Not worried about that. It's a known bug in Plex. 

https://forums.plex.tv/t/upgrade-to-server-1-41-1-9057-caused-the-video-codec-information-to-be-removed/891022/10

**Review by JonnyWong16 — APPROVED** [review]

**Pull request merged**
