### PR TITLE
conversion_actions

### PR DESCRIPTION
**Pull request by blacktwin**
Adding actions for Optimized and Conversion Items

Referencing Issue #130 

Actions:
- [x] Remove all optimized Items

- [x] Pause Conversions

- [x] Rename Optimized item

- [x] Remove Optimized item

- [x] Remove Conversion item

- [x] Move Conversion item's position in conversion queue

- [x] Create Optimized item

- [x] Reprocess removed Conversion that is still listed in Optimized items

--Pytest

- [x] Pytest create optimized media

- [x] Pytest check conversions and optimized items listing

- [x] Pytest remove conversion job and confirm optimized items listing exists

- [x] Pytest use optimized ID to reference back to original movie object

- [x] Pytest remove all optimized Items

### CODE REVIEW

**Comment by blacktwin** [comment]
Optimize will need some additional testing to confirm it's working as intended. Still need pytests setup.

**Comment by blacktwin** [comment]
Added test for optimizing test movie. Checks `conversions()` and `optimizedItems()` lists. Removes from `conversions()` and still exist in `optimizedItems()`. Use optimized ID to match back to original movie key.

**Comment by Hellowlol** [comment]
Looks good. Can you fix the failing tests (your own) and the your doc strings?

**Comment by blacktwin** [comment]
I thought I got all my docstrings? Any place in particular? Something need more information?

Last commit only fails for 3.6. Not sure why without seeing the UI. I have seen items fail when trying to optimize. Item will be in optimized listing but not in conversions. For some reason the file can't be optimized whether scripted or via UI. The video file will play fine but for whatever reason it will not optimize.

```python
    assert len(plex.optimizedItems()) == 1
    assert len(plex.conversions()) == 1 # failing
```

**Comment by Hellowlol** [comment]
check the flake test

**Comment by blacktwin** [comment]
Flake Tests are fine now. Still getting the same error when asserting the conversion list after creating a conversion/optimized item.

**Comment by Hellowlol** [comment]
Regarding  Still getting the same error when asserting the conversion list after creating a conversion/optimized item. Does this work locally? and you mark the tests as broken so we can get this shit merged :P

**Comment by blacktwin** [comment]
Works/passes locally and with other Python versions in Travis.

**Comment by blacktwin** [comment]
Ok to merge?

**Comment by blacktwin** [comment]
Ready for review @Hellowlol

**Pull request merged**
