### PR TITLE
Function update timeline for base.py

### PR DESCRIPTION
**Pull request by tijder**
Function to update the timeline for a payable item. With this the item will be showed in the now playing screen.

### CODE REVIEW

**Comment by pkkid** [comment]
Thanks! -- If you have a few extra minutes, can you add a test for this?  If not, that's fine, I'll add a test when I have time before merging this in.

**Comment by tijder** [comment]
I wrote a basic test. I only not familiar with python tests. I don't know how to write a test for testing if the timeline is added to the now playing screen.

**Comment by Hellowlol** [comment]
Can we just set the duration automatically if duration is omitted?
````
if duration is None:
    duration = self.duration
....
````

**Comment by tijder** [comment]
Good idea. I added it in the code.

**Pull request merged**
