### PR TITLE
Moved split to PlexPartialObject

### PR DESCRIPTION
**Pull request by darthShadow**
Moved split to PlexPartialObject so it's available for the Show object instead of the Episode object

### CODE REVIEW

**Comment by Hellowlol** [comment]
Isnt it possible to spilt a episode? I have to look into this

**Comment by JonnyWong16** [comment]
Split apart is only available for movies, tv shows, and artists.
https://support.plex.tv/articles/201018248-merge-or-split-items/

I *think* it might be available for albums? I'm not 100% sure.

**Comment by darthShadow** [comment]
I can confirm that it's available for Shows and Movies and not for Episodes as per the docs.

Can't check for Artists/Albums unfortunately but since they both inherit from the same PlexPartialObject Class, it shouldn't be a problem, even if they do support it.

**Comment by Hellowlol** [comment]
I don't want this added to PlexPartialObject since this class is used for other things that don't support split. The option is to just add this to every class that's need it to create a Mixin.

**Comment by Hellowlol** [comment]
@JonnyWong16 Does the same rule apply for merge?

**Comment by jjlawren** [comment]
@Hellowlol to clarify you'd like to close this PR and use the approach in #639 instead?

**Comment by Hellowlol** [comment]
Yes

**Pull request closed without merging**
