### PR TITLE
add MyPlexUserShares class

### PR DESCRIPTION
**Pull request by blacktwin**
I wanted to be able to see user shares from my server. 

`plex.myPlexAccount().users_shares(plex)[0].__dict__` will show data from https://plex.tv/api/servers/{machineId}/shared_servers.
seems redundant to use server object twice. Not sure how to work around that.

`plex.myPlexAccount().users_shares(plex)[0].shared_sections` will display shared sections in listed dict with section id, key, and name

```python 
print(plex.myPlexAccount().users_shares(plex)[0].shared_sections)

[   {   'id': 'xxxx', 'key': '16', 'name': 'Audio Books'},
    {   'id': 'xxxx', 'key': '14', 'name': 'Comedy Specials'},
    {   'id': 'xxxx', 'key': '2', 'name': 'Movies'},
    {   'id': 'xxxx', 'key': '12', 'name': 'Movies Anime'},
    {   'id': 'xxxx', 'key': '4', 'name': 'Music'},
    {   'id': 'xxxx', 'key': '3', 'name': 'TV Shows'},
    {   'id': 'xxxx', 'key': '11', 'name': 'TV Shows Anime'},
    {   'id': 'xxxx', 'key': '10', 'name': 'Workout'}]

```

looks like I might be a pull behind.

### CODE REVIEW

**Comment by pkkid** [comment]
This change looks good to me. @Hellowlol was working in that area more recently, so would like his input as well before we merge.

**Comment by Hellowlol** [comment]
So this pr isn't needed it should be supported atm but isn't since as i apparently haven't tested this good enough. Add is section as a last minute change. I wasnt aware that a Element was False...

Also the naming could probably be better. 

to get a users shared section you can do:
````
account = MyPlexAccount()
user = account.user('Hellowlol')
# servers is a list since you can share more servers
shared_sections = users.servers[0].sections()
````

**Comment by blacktwin** [comment]
Using your method:
```python
account = MyPlexAccount()
user = account.user('Hellowlol')
# servers is a list since you can share more servers
shared_sections = users.servers[0].sections()
```
Doesn't produce the desired output but you're saying the it's not yet supported?

**Comment by Hellowlol** [comment]
It was intented to be supported but wasnt since sections would always return a empty list. Now it returns a list of section objects where you have access to the same info as in your list of dicts and some more.

**Comment by Hellowlol** [comment]
You need to pull from master to use this feature btw.

**Comment by Hellowlol** [comment]
I think im gonna rename the sections as it doesnt describe it will some might think its the same library sections

**Comment by blacktwin** [comment]
Trying:
```python
account = plex.myPlexAccount()
user = account.user('username')
shared_sections = user.servers[0].sections()
print(shared_sections)
```
Produces:
```python
File "C:\Python27\lib\site-packages\plexapi\myplex.py", line 508, in sections
    if isinstance(section, ElementTree.Element):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```
Am I missing something? I've updated plexapi just before running.

**Comment by Hellowlol** [comment]
I'm sure I tested this before I merged. Can you try with python 3?

**Comment by Hellowlol** [comment]
Anyway I'll fix this later today. If you figure this you can send a pr

**Comment by Hellowlol** [comment]
It was a python2 bug. Its fixed now.

**Comment by blacktwin** [comment]
Wow! Very NICE! Thanks!

**Pull request closed without merging**
