### PR TITLE
Multiple things added

### PR DESCRIPTION
**Pull request by tijder**
I like to merge my downsteams change back to this project. The things I added are:
- Music clip support
- Load playqueue from url and refresh playqueue
- Change subtitle and audio stream
- Get download url for subtitle stream

### CODE REVIEW

**Comment by Hellowlol** [comment]
Thanks for the PR. Sorry for leaving this for a _really_ long time. Now this was pretty PR with loads of different things in. Honestly I'm not interested in everything and something has already been added. I'll try to come back to this later and  cherrypick the things about playqueue and playlist

**Comment by blacktwin** [comment]
@Hellowlol the `Clip` class has already been added but this version looks more complete. Might be worth looking at too.

**Comment by Hellowlol** [comment]
If you plan to set this merged you need to make a pr for each future feature with a test. There is no way I’m merging this as there to many different parts.

**Comment by tijder** [comment]
Sorry, then I close this issue. When I have time I will create a pull request for each feature.

**Pull request closed without merging**
