### PR TITLE
matching_fix

### PR DESCRIPTION
**Pull request by blacktwin**
Corrections to PR #436 found in Issue #140

### CODE REVIEW

**Comment by Hellowlol** [comment]
This ready?

**Comment by blacktwin** [comment]
Not yet.

**Comment by blacktwin** [comment]
Here is some testing to examine the key that is being used during the query.

```
I Have a Dream speech by Martin Luther King .Jr HD (subtitled)

item.matches()
/library/metadata/111656/matches
[<SearchResult:I-Have-a-Dream-Speec:100>]

item.matches(year='')
/library/metadata/111656/matches?manual=1&language=xn&agent=com.plexapp.agents.youtube
[<SearchResult:I-Have-a-Dream-speec:80>]

item.matches(title='')
/library/metadata/111656/matches?manual=1&language=xn&agent=com.plexapp.agents.youtube
[<SearchResult:I-Have-a-Dream-speec:80>]

item.matches(year='', title='')
/library/metadata/111656/matches?manual=1&language=xn&agent=com.plexapp.agents.youtube
[<SearchResult:I-Have-a-Dream-speec:80>]

item.matches(agent='youtube')
/library/metadata/111656/matches?manual=1&language=xn&agent=com.plexapp.agents.youtube
[<SearchResult:I-Have-a-Dream-speec:80>]

item.matches(agent='youtube', title='TEST')
/library/metadata/111656/matches?manual=1&title=TEST&language=xn&agent=com.plexapp.agents.youtube
[<SearchResult:I-Have-a-Dream-speec:80>]
```

These keys match what we see when using the webui.

**Comment by blacktwin** [comment]
For an accurate set of test we should be examining the key/url used in the query. Although once passed how would we get this information?

**Comment by Hellowlol** [comment]
Check the _initpath

**Pull request merged**
