### PR TITLE
Library section id for all

### PR DESCRIPTION
**Pull request by andrey-yantsen**
It's a quite controversial change, but for now I have no idea how to do this thing better. Basically `librarySectionID` field should be added automatically for any item if the field exists in metadata, and that's what I'm trying to achieve here.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Why Is this needed?

**Comment by andrey-yantsen** [comment]
@Hellowlol there are photos in a library which not belong to any albums (and probably albums are not a thing anymore), and for those photos you can't get a `librarySectionID` in a nice&easy way. Without the field you can't create playlist with those photos, or send them to sync.

At least `Photo.section()` fails when the photo received from `PhotoSection.all()`.

**Comment by andrey-yantsen** [comment]
Problem occurs at least on with PMS v1.13.5.5332. Of course there is a huge chance that I'm doing anything wrong, but I really hope that it's not the case this time :)

**Comment by andrey-yantsen** [comment]
Here is a short piece of code (from py.test) which fails with exception about unknown library:
```python
def test_playlist_photos(plex, photos):
    items = photos.all()
    assert plex.createPlaylist('Photos', items)
```

**Comment by Hellowlol** [comment]
Im gonna put this on hold for a while, i want to see if we can do this another way. This touches parts of code that needs to be fast as its used pretty much everywhere.

**Comment by andrey-yantsen** [comment]
> Im gonna put this on hold for a while, i want to see if we can do this another way.

Yep, I really hope we find a better way :) But anyway — when we receiving a MediaContainer IMO we should parse all of its attributes, not just processing internal items and abandoning all the meta. E.g. for `library.section('Photos').all()` I'm receiving following meta:

```xml
<MediaContainer allowSync="1" art="/:/resources/photo-fanart.jpg" identifier="com.plexapp.plugins.library" librarySectionID="4" librarySectionTitle="Photos" librarySectionUUID="2a550866-7060-4612-9f64-2b7b4e0a82b7" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1534566129" nocache="1" size="10" thumb="/:/resources/photo.png" title1="Photos" title2="All Photos" viewGroup="photo" viewMode="131633">
```

And at least 3 attributes are pretty much useful for me: `allowSync`, `librarySectionID` and `librarySectionUUID`. Also `librarySectionUUID` would be helpful when creating new playlists. Looks like `fetchItems` should return a some kind of `MediaContainer` object, exactly as it is in the API.

> Who creates a playlist for images anyway? :P

In latest version of Plex "playlist for images" used as albums :( And also you can't sent selection of photos without library ID to sync.

@Hellowlol I've made another try on this, this time it doesn't have this huge side-effect, please take a look on 5d9df1a.

**Comment by andrey-yantsen** [comment]
Yep. Without this one you can't properly work (create playlists, set up mobile sync) with photos which stored outside of any albums.

**Comment by Hellowlol** [comment]
Still dont like it but lets go for it.

**Pull request merged**
