### PR TITLE
Add collectionMode data and modeUpdate

### PR DESCRIPTION
**Pull request by blacktwin**
Added collectionMode to collection data. 
modUpdate acts like webUI, `collection.modeUpdate(mode="default")`

### CODE REVIEW

**Comment by Hellowlol** [comment]
Can you add a test and docs string?

**Comment by blacktwin** [comment]
docstrings are added. Not sure about what you'd want for the tests. I'll look into it.

**Comment by blacktwin** [comment]
I'm guessing this fails because there are either no Collections or they aren't enabled in the test environment. Should I add a test to create a collection? test_actions or test_library?

**Comment by Hellowlol** [comment]
I would prefer it was added to the class you have added it to. Dunno why exists a action. I have tried to follow a format when i added the initial tests. test_pyfile_Classname_method

**Comment by blacktwin** [comment]
I think this is one is ready.

**Pull request merged**
