### PR TITLE
updateFriend() all sections if None

### PR DESCRIPTION
**Pull request by blacktwin**
Update to updateFriend() ad _getSectionIds() to allow for all sections to be selected with None are identified.
related issue #346

### CODE REVIEW

**Comment by pkkid** [comment]
The failed checks all look audio related and I suspect unrelated to anything you changed?

**Comment by blacktwin** [comment]
Might need to update `inviteFriend` to use `server` instead of `machineIdentifier` also.

**Comment by Hellowlol** [comment]
Mind sending a PR that update the docs?

**Comment by blacktwin** [comment]
Created a new PR as to have to have backtrack and cleanup this one. Hope thats ok. This PR can be closed.

**Pull request closed without merging**
