### PR TITLE
allow for title and unwatched filters

### PR DESCRIPTION
**Pull request by blacktwin**
Addressing issue #221

### CODE REVIEW

**Comment by pkkid** [comment]
It's small, but this is an API breaking change and needs the major version incremented before pushing to pypi.

**Comment by blacktwin** [comment]
Sorry for being naive, but why, how? And what can I do to assist?

**Comment by pkkid** [comment]
Not naive, just that a variable name change in a function definition will break existing code. If someone is calling that function and specifying `playlistTitle=something`, that will break if they update to whatever version of the code this change lands in. We when we update pypi, we just need to make sure we update the major version number so they know to expect these types of changes.

**Comment by blacktwin** [comment]
@Hellowlol With the exception of aforementioned major version update, is there anything else I can do for this PR?

**Comment by Hellowlol** [comment]
This dont seems to be a breaking change? He didnt change a keyword argument. Why was the title changed btw?

**Comment by blacktwin** [comment]
> Why was the title changed btw?

The change would allow for the use of kwarg `title=` for filtering. 
```python
# Currently
plex.createPlaylist(title="Naming of Playlist", title="Title Filter") # will not work
plex.createPlaylist(title="Naming of Playlist", **{"title":"Title Filter"}) # will work
# PR
plex.createPlaylist(playlistTitle="Naming of Playlist", title="Title Filter")
plex.createPlaylist(playlistTitle="Naming of Playlist", **{"title":"Title Filter"})
```

**Comment by Hellowlol** [comment]
Ah, i forgot about smart playlists. In the mean time lets just push this back to the next version. Its possible to handle  this correctly by using _createSmart

**Comment by JonnyWong16** [comment]
Changed in #763.

**Pull request closed without merging**
