### PR TITLE
Add new collection attributes

### PR DESCRIPTION
**Pull request by JonnyWong16**
## Description

Add new collection attributes related to smart collections. Actual support for creating smart collections to come later.

Seasons, episodes, and tracks can also be added to collections now.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods
- [x] I have added tests when applicable

### CODE REVIEW

**Comment by meisnate12** [comment]
collectionPublished will cause a ValueError to be thrown whenever you access the collection if anything besides 0 or 1 is stored in the field (which is currently possible)

**Comment by JonnyWong16** [comment]
Don't put random numbers in the setting... Plex has already said that the input box in the UI is an error and they will be removing it.

**Comment by meisnate12** [comment]
gotcha I was testing if the number there had anything to do with whether or not a collection was published on the homepage and just noticed that it caused this error so just figured I'd let you know

**Comment by JonnyWong16** [comment]
It's a bool, so it's only 1 (True) or 0 (False).

**Comment by meisnate12** [comment]
It's just that the average user doesn't know that so if someone just puts something there not knowing any better and then tries to run a script that loads that collection it's going to error every time the script tries to access that collection. While it may be a bool the UI looks like a string and allows a string value to be stored there so I feel at the very least this shouldn't error just trying to load the collection when there is a string.

**Comment by JonnyWong16** [comment]
1. I'm just letting you know that it's a bool, not saying everyone needs to know.
2. Plex has already said they are removing it from the UI.
3. This hasn't been merged yet, so there is no issue with anyone accidentally using it.

**Pull request merged**
