### PR TITLE
Add support for AlertListener receiving errors

### PR DESCRIPTION
**Pull request by glensc**
## Description

Add support for AlertListener receiving errors

Use the NodeJs like `callback(success, error)` signature for distinguishing errors from data.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

### CODE REVIEW

**Comment by glensc** [comment]
This is a somewhat breaking change, listeners may receive now `None` as data.

What do you think of this API? or better make the change not breaking change? for example have two callback parameters for the AlertListener constructor?

**Comment by Hellowlol** [comment]
I dont like it. Dumping a exception as a string is kinda useless imo

**Comment by JonnyWong16** [comment]
I don't like the `self._callback(data, None)` and `self._callback(None, err)`. Passing around `None` like that seems very "unpythonic".

If this is implemented, I would prefer having two different callback functions. It's cleaner and isn't a breaking change.

```py
AlertListener(callback, callbackError)
```

The only use case I can think of for having two different callback functions is to log the error message to your own application. The error isn't a Plex error, it's a websocket client error.

**Comment by Hellowlol** [comment]
The user can log what they want inside the callback.

**Comment by glensc** [comment]
I use this event to reset caches, as likely server was restart. as plex sessions watch are dumb incremental numbers. they will conflict if server restart.

**Comment by Hellowlol** [comment]
If you need a robust way to connect to pms using websocket you could use another package. I needed ut using another one as i wanted one that always reconnect when the connection drops.

https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/plex.py#L1308-L1322

**Comment by glensc** [comment]
Replaced by https://github.com/pkkid/python-plexapi/pull/850

**Pull request closed without merging**
