### PR TITLE
Replaced friends route with v2 counter-part

### LINKED ISSUE #1412: Problems with DELETE USER
### Describe the Bug

Does anyone have problems with the DELETE USER endpoint?

plextemp.myPlexAccount().removeFriend(email or user)

BadRequest: (410) gone; https://plex.tv/api/friends/333526617 <?xml version="1.0" encoding="UTF-8"?> <Response code="410" status="This endpoint was deprecated and removed"/>

### Code Snippets

_No response_

### Expected Behavior

_No response_

### Additional Context

_No response_

### Operating System and Version

Ubuntu 20.04

### Plex Media Server Version

1.24.27.33

### Python Version

3.8.17

### PlexAPI Version

4.7.2

### PR DESCRIPTION
**Pull request by JamsRepos**
## Description

Plex has decided to deprecate the old route from the v1 API, this replaces it with it's v2 counter-part.

Fixes #1412 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

### CODE REVIEW

**Comment by JamsRepos** [comment]
Do note; I have tested this in both put and delete cases.

**Comment by JamsRepos** [comment]
> where is that v2 API i cant found it thanks bro for your help

Not quite sure what you mean? You find this endpoint by performing the action on the browser then checking which API call is called.

**Comment by JamsRepos** [comment]
Yeah, Plex does not disclose their API or their changes for it. So it's just a case of waiting for them to deprecate it hence this PR.

**Comment by JonnyWong16** [comment]
Where do you see `https://plex.tv/api/v2/sharings/<userId>`?

I see these two URLs when editing shared libraries/restrictions for another user in Plex Web.
* `https://clients.plex.tv/api/v2/shared_servers/<sharedServerId>`
* `https://clients.plex.tv/api/v2/sharing_settings`

**Comment by JamsRepos** [comment]
> Where do you see `https://plex.tv/api/v2/sharings/<userId>`?
> 
> I see these two URLs when editing shared libraries/restrictions for another user in Plex Web.
> 
>     * `https://clients.plex.tv/api/v2/shared_servers/<sharedServerId>`
> 
>     * `https://clients.plex.tv/api/v2/sharing_settings`

Remove a user from your server and you'll get the sharings endpoint. I then tried to update a user and the endpoint also worked there too. 

May require additional testing now though as for the most part I've forgotten.

**Comment by mtrogman** [comment]
Good Afternoon,
Is there any further validation or requirements to get this PR merged?  I can happily help as this broke automation I have in place and I would love to get this working again.

**Comment by JonnyWong16** [comment]
I am merging this but only indicating that it is a temporary fix.

The URL used here _does not_ match what Plex Web is using for update shared libraries/restrictions. So it is uncertain whether this is actually intended/supported and it may break again at any moment.

**Pull request merged**
