### PR TITLE
add exists function

### PR DESCRIPTION
**Pull request by blacktwin**
instead of modifying media.py and base.py, create a function to check if the video exists, is accessible, and which file if multiples exist(ed). For #385

### CODE REVIEW

**Comment by blacktwin** [comment]
First attempt at this issue. media.py and base.py can be updated for if exists. This was my minimal impact solution.

**Comment by Hellowlol** [comment]
I would prefer if the we just add the missing attributes and require a manual reload.

**Comment by blacktwin** [comment]
Yeah, I was thinking the same. What about the exists function for the video object?

**Comment by blacktwin** [comment]
#385 exists and accessible will be cast to Boolean values. Video objects can pull this information along with which file the states are referring too with `video.exists()`. Not the prettiest return but I think it serves. Also added tests to validate the updated attributes.

**Comment by Hellowlol** [comment]
Im not that fond of the exists function. I think it’s to general as you could end up with a part that is accessible and one that isn’t (2 files stored on different location) if a user want to check this they can use iterParts() and check what they want.

**Comment by blacktwin** [comment]
Sounds good to me. I just figured it'd be a quicker solution to find that kind of information by accessing it at the video object vs media. It can be removed.

**Pull request merged**
