### PR TITLE
Home user and remove sections

### PR DESCRIPTION
**Pull request by blacktwin**
def updateFriend() update to allow for removing sections if `remove_sections=True`. 

def user() update to find Home user names.

### CODE REVIEW

**Comment by blacktwin** [comment]
Didn't test enough. Unable to add shares after remove_sections=True.

**Comment by Hellowlol** [comment]
I'd prefere if remove section is true. Since a lot of things are thruthy. Can you update the doc string?

**Comment by pkkid** [comment]
Also, to stick with our camelCase formating it should be removeSections instead of remove_sections.

**Comment by pkkid** [comment]
@Hellowlol Are you good with this one? I don't quite understand this area enough.

**Comment by Hellowlol** [comment]
Honestly i cant even remember there being a update friend method. It looks like my code but i cant remember the name. As long as it works ill say merge it and ill go back and add a test for this later.

**Pull request merged**
