### PR TITLE
new_hubs

### PR DESCRIPTION
**Pull request by blacktwin**
Allow for pulling information from hub sections
Disclaimer, Token will need to be pulled from web browser session using app.plex.tv.

### CODE REVIEW

**Comment by pkkid** [comment]
Wow you're fast! Is this already ready to go?

**Comment by blacktwin** [comment]
Kinda. I'm not 100% sure about where I put everything. Would appreciate any feedback. It pulls the information fine but I think there is more to add as well.

**Comment by blacktwin** [comment]
Much faster in returning the maximum amount of Hubs within the providers.

**Comment by blacktwin** [comment]
I'd like to find a way to get [this](https://old.reddit.com/r/PleX/comments/e6ocvc/a_complete_list_of_movies_available_from_plex/?st=k3tlup0n&sh=d7fdc3c5) in there too.

**Comment by mcqweb** [comment]
> I'd like to find a way to get [this](https://old.reddit.com/r/PleX/comments/e6ocvc/a_complete_list_of_movies_available_from_plex/?st=k3tlup0n&sh=d7fdc3c5) in there too.

Just added the paging to that too now so it genuinely should be the full list (of unwatched anyway)

**Comment by blacktwin** [comment]
I think this is good for now. The ability to query all available free items is available if you want and the additions return what Plex returns.

**Comment by blacktwin** [comment]
I'm stomped. The new endpoint defined in myplex.py will return the xml with 
```python
requests.get(VOD, params={'X-Plex-Token':TOKEN})
```
but not when using the methods added to this PR. Any help would be very appreciated.

**Comment by Hellowlol** [comment]
All logging and simplify. Are you use the end point support the plex x container param etc. use fetch items directly

**Comment by blacktwin** [comment]
> Are you use the end point support the plex x container param etc 

Yes.

>is the token required to be in the url? 

Yes.

I'll looking into logging and see what I get.

**Comment by Hellowlol** [comment]
The token is probably the reason why it don’t work. The token is added in the header not the url (see the class.query) Some endpoint require different stuff

**Comment by blacktwin** [comment]
This works:
```python
    def webShows(self, maxresults=50):
        """ Returns a list of Webshow Hub items :class:`~plexapi.library.Hub`
		"""
        req = requests.get(self.WEBSHOWS, headers={'X-Plex-Token':self._token})
        elem = ElementTree.fromstring(req.text)
        return self.findItems(elem)
```
but not:
```python
self.query(self.WEBSHOWS)
```
Which was the method I used [before ](bd2519b35b6c2a6b133d20b5fe7d45c6dcbd70a4)and it definitely did work. Very odd.

So I guess I'll go with the working method above.

**Comment by blacktwin** [comment]
From digging into these endpoints more we may want to build out another section for `providers`. Which are outside media items sources.
```python
    VOD = 'https://vod.provider.plex.tv/hubs/'
    WEBSHOWS = 'https://webshows.provider.plex.tv/hubs/'
    NEWS = 'https://news.provider.plex.tv/hubs/'
    PODCASTS = 'https://podcasts.provider.plex.tv/hubs/'
    MUSIC = 'https://music.provider.plex.tv/hubs/'
    METADATA = 'https://metadata.provider.plex.tv/'  
```
`METADATA` being the endpoint to pull additional information from these outside sources. [Example](https://old.reddit.com/r/PleX/comments/edm420/api_for_the_newish_songs_in_this_episode_feature/fghpf2y/). 

Each provider endpoint can branch off from it initial root `*.provider.plex.tv` using the `key` tags in the xml. Example being `/hubs/sections/home/popular` would show the popular podcasts/news/etc. Selecting a single items from that list and using it's `key` tag and appending it to the `METADATA` endpoint would provide all the metadata for that item.

**Comment by blacktwin** [comment]
Now everything is pulling basic Hub information. I think this is a good start but there is definitely more that can be added as far as the sub Items inside each Hub endpoint as mentioned above. I think that can be left for another PR as I think it will require a lot more changes. 

Let me know if there needs any changes, suggestions, tests, etc. I'd like to close this to start working on other issues/requests and come back to adding more of the sub Item work.

**Comment by blacktwin** [comment]
Ready for review @Hellowlol

**Pull request merged**
