### PR TITLE
poster_change

### PR DESCRIPTION
**Pull request by blacktwin**
Allow for selecting a poster from the available list of posters. Allow for uploading posters from url or filepath.
From issue #179
Poster selection currently causes a parser error
```
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```
but the poster will still be selected.

### CODE REVIEW

**Comment by Hellowlol** [comment]
If plex returns junk xml but the request still succeeds, just catch and swallow the exception.

**Comment by Hellowlol** [comment]
Is the poster option only available for video files or is it possible to do this on albums etc?

**Comment by blacktwin** [comment]
> If plex returns junk xml but the request still succeeds, just catch and swallow the exception.

it returns the new thumb path. `/library/metadata/80584/thumb/1584129784` So I'd assume make the changes in the server.py?

> Is the poster option only available for video files or is it possible to do this on albums etc?

I'll check. If so I'll add the method to the appropriate class(s).

**Comment by blacktwin** [comment]
Moved everything to base.py. Now artists, albums, videos, movies, shows, etc should be covered.

**Comment by Hellowlol** [comment]
Maybe you need to create another class to add your methods to. The plexpartial class uses several places. Can you doble check that we dont have any unwanted side effects? (Like the method is available somewhere it shouldn’t.)

**Comment by blacktwin** [comment]
> If plex returns junk xml but the request still succeeds, just catch and swallow the exception.

My solution so far is to update the server.py `query` method's return from:
`return ElementTree.fromstring(data) if data.strip() else None`
to 
`return ElementTree.fromstring(data) if data.strip() and response.encoding else None`
The poster selection method returns `response.encoding = None` so this is one why of silencing the error.

**Comment by blacktwin** [comment]
> Maybe you need to create another class to add your methods to. The plexpartial class uses several places. Can you doble check that we dont have any unwanted side effects? (Like the method is available somewhere it shouldn’t.)

Looks to only be used in location where posters would exist. `Playlist` maybe not, but IIRC you can hack the poster of a `Playlist`. 
image

**Comment by blacktwin** [comment]
Also to note with changing the poster in Playlists, the poster you change to is also the faded background art.

**Comment by blacktwin** [comment]
Ready for review @Hellowlol . This PR will allow for updating posters and art.

**Pull request merged**
