### PR TITLE
Feature: Expose total_size in fetchItems()

### PR DESCRIPTION
**Pull request by glensc**
## Description

Add a way to get total for the search:

```py
maxresults = section.searchEpisodes(maxresults=0)
total_size = maxresults.total_size
```
- https://github.com/Taxel/PlexTraktSync/pull/1578

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

### CODE REVIEW

**Comment by glensc** [comment]
Maybe PlexAPI way of doing things is to add `returnTotalSize=True` kwarg instead?

**Comment by glensc** [comment]
@JonnyWong16 tests pass now. but I think this change is too invasive. maybe even has small performance impact.

but any other recommendation on how to get container size? with optimal way? basically need to send query with limit=0, so it 
 (pms) would only report totalSize.

what you think of refactoring those parts of using yield rather array merging? as that's what I'm trying to solve initially:
- https://github.com/Taxel/PlexTraktSync/pull/1578

**Comment by JonnyWong16** [comment]
Honestly, the public method `LibrarySection.totalViewSize(libtype="episode")` is preferred.

If you really need this then best to keep it simple and just add something like a `self._fetchTotalSize` attribute to the base object as a cache. Then you need to be very careful when you access the attribute because it will update every time `fetchItems` is called.

**Comment by glensc** [comment]
I was confused by your statement:
> Honestly, the public method LibrarySection.totalViewSize(libtype="episode") is preferred.

seems `totalViewSize` method already exists:
- https://github.com/pkkid/python-plexapi/blob/7da49eb711663f8b4e2cebcac41298c6324c1427/plexapi/library.py#L475

**Comment by glensc** [comment]
existing method works:
- [Taxel/PlexTraktSync@`ef93d07` (#1578)](https://github.com/Taxel/PlexTraktSync/pull/1578/commits/ef93d07206400f7b1b2b60e0e42d6ea6fd10af8a)

this mr is not needed.

**Pull request closed without merging**
