### PR TITLE
Add codecov configuration

### PR DESCRIPTION
**Pull request by jjlawren**
Set some thresholds, skip automated comments to PRs.

### CODE REVIEW

**Comment by Hellowlol** [comment]
I like the automated message as i quickly can see of we miss anything

**Comment by jjlawren** [comment]
This should still enforce some thresholds but won't put the (large) comment in every PR. It feels a bit obtrusive to me but I'm not against keeping it if you see value.

**Comment by jjlawren** [comment]
Unfortunately the PR coverage is always going to drop comparing against `master` since it only runs the unclaimed tests. Not sure of a clean way to address that.

**Comment by JonnyWong16** [comment]
We can split up the coverage reports to `unclaimed` and `claimed`.

See workflow here:
https://github.com/JonnyWong16/python-plexapi/actions/runs/424907307

I don't think anything needs to be changed for the codecov pull requests comments? Only unclaimed reports will be uploaded for pull requests so it should only comment unclaimed coverage.

**Pull request merged**
